### ISSUE TITLE
`tests` folder is installed with the package

### ISSUE THREAD

**Issue by bonastreyair** [hvalev/py-markdown-table#10]
https://github.com/hvalev/py-markdown-table/blob/d1ecd0f18a700df818433015e82d5a40638bd768/setup.py#L14

This line of code also finds the "tests" folder and it installs it as a package.

When developing in another repo and importing from my own `tests` folder it first finds your silently installed `tests` package before my folder. 

As a workaround I needed to play with `sys.path` to first find my folder but that should not be the way of doing and wanted to fix the issue from its source root.

**Comment by hvalev** [comment]
Check my comment in your PR and if the new changes solve your issue, feel free to close this.

**Comment by bonastreyair** [comment]
yeah it seems like it works now, thanks! 

although I think that the file `setup.py` can now be deleted since it can cause confusion (it says v0.4.0 and it is no longer used, right?)
