### ISSUE TITLE
Add possibility to set the column alignment for the rendered cell

### ISSUE THREAD

**Issue by q-wertz** [hvalev/py-markdown-table#12]
Currently it is not possible (as far as I understand it) to set the alignment of the rendered cell column wise.

This would require to "adjust" the second line of the markdown output with colons (see e.g. https://vuepressbook.com/tutorial/tutorial5.html#aligning-text-within-columns)

It would be nice to have a configuration option similar to the one of `multiline` where one can set the alignment per column name as `dict[str, Literal["left","right","center"]]` where the default is `"left"`.

**Comment by hvalev** [comment]
@q-wertz I just added that feature in the newest 1.1.0 release. I've updated the examples in the readme if you want to see some hands-on input/output. I'll close this issue now. Feel free to re-open it if you notice anything odd.

**Comment by q-wertz** [comment]
Thanks a lot for the fast response and implementation :)

As I understand it, now it is possible to set the padding with and weight per column and also seems to work:

```python
from py_markdown_table.markdown_table import markdown_table

test = [
    {"aasdff": 3, "basdfasdf": 5, "casdfasdf":19},
    {"aasdff": 7, "basdfasdf": 9, "casdfasdf":19}
]

markdown_table(test).set_params(
    row_sep="markdown",
    quote=False,
    float_rounding=4,
    padding_weight={"aasdff": "centerleft", "basdfasdf": "centerright", "casdfasdf": "left"},
    padding_width={"aasdff": 5, "basdfasdf": 7, "casdfasdf": 8},
).get_markdown()
```
Output:
```text
|aasdff|basdfasdf| casdfasdf|
|------|---------|----------|
|   3  |    5    |        19|
|   7  |    9    |        19|
```

But what I meant is a setting to the markdown table renderer. This is usually done by colon characters.

The case above should (in "markdown" style) then should look like:
```text
|aasdff|basdfasdf| casdfasdf|
|:----:|:-------:|---------:|
|   3  |    5    |        19|
|   7  |    9    |        19|
```
(There is no difference between `centerleft` and `centerright`)

Interpreters then let the table look like:
![image](https://github.com/user-attachments/assets/0f3c48dd-093f-4644-a7b5-c86470ca7711)

**Comment by hvalev** [comment]
Ah, I see what you mean. Indeed, the padding parameters do not mirror the alignment ones of github. The reason for that is those alignment parameters are not part of the standard markdown syntax and would not translate to other renderers and I'd like to keep this library self-contained and generic. You can check out the discussion in this issue #4 as this point has been raised before.

**Comment by q-wertz** [comment]
Ah ok I understand. Thanks. Didn't see that issue.
