### ISSUE TITLE
Value Error for when adding links in the table.

### ISSUE THREAD

**Issue by jitendra42** [hvalev/py-markdown-table#7]
If we create a link in a table `[link] (url)`,  as URLs are long & single string,  Its pretty much always throws Value Error when clearly there is no need.
https://github.com/hvalev/py-markdown-table/blob/main/py_markdown_table/markdown_table.py#L276

Posible solution could be to detect url & ignore them, but i would say completely remove the Value error check also will also fine

**Comment by hvalev** [comment]
I've released a new version of the package that includes a `skip_data_validation` parameter for this purpose. Let me know if it works for you.
